### Puxar base de dados

In [1]:
import pandas as pd

Tabela_df = pd.read_csv("exportacoes_franca.csv")
display(Tabela_df)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

### Informações Gerais

Quantas linhas têm a tabela? Existe algum valor vazio que deveria ser tratado?

In [2]:
display(Tabela_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  str
 3   City             142360 non-null  str
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  str
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  str
 8   Economic Block   142360 non-null  str
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), str(5)
memory usage: 11.9 MB

None

### Como foi a evolução das exportações para a frança ao longo dos anos?

Crie uma tabela com os anos de 2016, 2017, 2018, 2019 e 2020 e o valor US$ de exportações

In [21]:
Exportacoes_df = Tabela_df[["Year","US$ FOB"]]
Exportacoes_df= Exportacoes_df.groupby("Year").sum(numeric_only=True)
display(Exportacoes_df)

         US$ FOB
Year
2016  4615500082
2017  4448705456
2018  5239424416
2019  5218723612
2020  3967594810

### Quais os produtos mais exportados ao longo de todo o período?

Queremos saber os produtos com maior valor US$ de exportação

In [26]:
Produtos_exportados_df = Tabela_df[["SH2 Description","US$ FOB"]]
Produtos_exportados_df = Produtos_exportados_df.groupby("SH2 Description").sum(numeric_only=True)
Produtos_exportados_df = Produtos_exportados_df.sort_values(by = "US$ FOB", ascending=False)
display(Produtos_exportados_df)

                                                       US$ FOB
SH2 Description
Residues and waste from the food industries; ot...  5641498484
Ores, slag and ash                                  3404353274
Nuclear reactors, boilers, machinery and mechan...  1889781694
Pulp of wood or of other fibrous cellulosic mat...  1855424642
Aircraft, spacecraft, and parts thereof             1253007710
...                                                        ...
Umbrellas, sun umbrellas, walking-sticks, seat-...       18872
Cork and articles of cork                                10974
Wool, fine or coarse animal hair; horsehair yar...        2540
Tin and articles thereof                                  2460
Photographic or cinematographic goods                      148

[97 rows x 1 columns]

### Em 2020 qual cidade mais exportou para a França?
Em valores US$

In [57]:
Exportacoes2020 = Tabela_df["Year"] == 2020
Exportacoes2020_df = Tabela_df[Exportacoes2020]
Exportacoes2020Filtro_df = Exportacoes2020_df[["City","US$ FOB"]]
Exportacoes2020Filtro_df = Exportacoes2020Filtro_df.groupby("City", as_index=False).sum(numeric_only=True)
Exportacoes2020Filtro_df = Exportacoes2020Filtro_df.sort_values(by="US$ FOB", ascending=False)
display(Exportacoes2020Filtro_df)
print(f"Cidade que mais Exportou para a França {Exportacoes2020Filtro_df.iloc[0]["City"]}")

                            City    US$ FOB
180         Duque de Caxias - RJ  279405596
326  Luís Eduardo Magalhães - BA  265328132
456            Ponta Grossa - PR  187777016
576     São José dos Campos - SP  172939276
508          Rio de Janeiro - RJ  122522214
..                           ...        ...
393            Não-Me-Toque - RS         42
164                 Cubatão - SP         40
226                Holambra - SP         10
587    São Sebastião do Caí - RS          6
489           Quatro Pontes - PR          0

[648 rows x 2 columns]

Cidade que mais Exportou para a França Duque de Caxias - RJ

### Quais os produtos mais exportados (em US$) que as 2 maiores cidades (em exportação em 2020) exportaram?

In [ ]:
cidade_df = Exportacoes2020_df[["City","SH2 Description","US$ FOB"]]
display(cidade_df)

Os produtos mais exportados em 2020 são :Residues and waste from the food industries; others e :Ores, slag and ash